export const fakeDataCategory = [
  {
    darkColor: '#888a3d',
    lightColor: '#8f9140',
    title: 'Règne Animal',
    logo: 'animal.png',
    id: 'animal',
    description: 'Nos amis les bêtes ne sont pas en reste avec cette catégorie',
    active: true,
  },
  {
    darkColor: '#01a778',
    lightColor: '#f33501',
    title: 'Annonce Dayloo',
    logo: 'dayloo.png',
    id: 'dayloo_annonce',
    description: 'Réservé aux annonces importantes',
    active: true,
  },
  {
    darkColor: '#e45e8a',
    lightColor: '#e72767',
    title: 'Formule',
    logo: 'formule.png',
    id: 'formule',
    description: 'Physique, Chimie, Maths... Les grandes formules qui régissent le monde',
    active: true,
  },
  {
    darkColor: '#cab749',
    lightColor: '#e9c707',
    title: 'Géographie',
    logo: 'geographie.png',
    id: 'geographie',
    description: 'Découvrons un pays, avec ses informations clés',
    active: true,
  },
  {
    darkColor: '#927dca',
    lightColor: '#6B5B95',
    title: 'Grammaire',
    logo: 'grammaire.png',
    id: 'grammaire',
    description: 'Révisons ensemble toutes les règles de grammaire',
    active: true,
  },
  {
    darkColor: '#83c662',
    lightColor: '#79C753',
    title: 'Histoire',
    logo: 'histoire.png',
    id: 'histoire',
    description: 'Un événement historique majeur avec quelques faits marquants',
    active: true,
  },
  {
    darkColor: '#ff9933',
    lightColor: '#FE840E',
    title: 'IA : Apprentissage',
    logo: 'ia.png',
    id: 'ia_apprentissage',
    description: "Découvrez les concepts de l'IA, du machine learning au deep learning",
    active: false,
  },
  {
    darkColor: '#d95959',
    lightColor: '#944743',
    title: 'Invention',
    logo: 'invention.png',
    id: 'invention',
    description: 'Qui a découvert quoi, quand et pourquoi ?',
    active: true,
  },
  {
    darkColor: '#fba693',
    lightColor: '#FA9A85',
    title: 'Littérature',
    logo: 'litterature.png',
    id: 'litterature',
    description: 'Un auteur célèbre, quelques faits marquants et ses ouvrages principaux',
    active: true,
  },
  {
    darkColor: '#cb4325',
    lightColor: '#CC4425',
    title: 'Taverne des spores',
    logo: 'taverne_des_spores.png',
    id: 'taverne_des_spores',
    description: 'Une spore (courte nouvelle de 600 signes), de la taverne des spores',
    active: true,
  },
  {
    darkColor: '#4abf8a',
    lightColor: '#3D9970',
    title: 'Vocabulaire Fantasy',
    logo: 'vocabulaire.png',
    id: 'vocabulaire_hf',
    description: 'Des mots de vocabulaires propres à la Fantasy !',
    active: true,
  },
  {
    darkColor: '#40dddd',
    lightColor: '#35bbbb',
    title: 'Vocabulaire Science Fiction',
    logo: 'vocabulaire.png',
    id: 'vocabulaire_sf',
    description: 'Des mots de vocabulaires propres à la Science Fiction !',
    active: true,
  },
];
